<?php

/**
 * @file
 * Normal module functions.
 */

/**
 * Implements hook_menu().
 */
function islandora_dimensions_menu() {
  return array(
    'admin/islandora/tools/badges/dimensions' => array(
      'title' => 'Dimensions.ai',
      'description' => 'Configure Dimensions.ai integration.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_dimensions_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_dimensions_block_info() {
  return array(
    'islandora_dimensions_badge' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora Dimensions Badge'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_dimensions_block_view($delta = '') {
  module_load_include('inc', 'islandora_badges', 'includes/utilities');
  $to_render = array();

  if ($delta == 'islandora_dimensions_badge') {
      $object = menu_get_object('islandora_object', 2);
      if ($object) {
        if (islandora_badges_show_for_cmodel($object)) {
          $doi = islandora_badges_get_doi($object);
          if ($doi) {
            $badge_style = variable_get('islandora_dimensions_badge', 'small_rectangle');
            $embed_code = '<span class="__dimensions_badge_embed__" 
                           data-doi="' . $doi . '" 
                           data-hide-zero-citations="true" 
                           data-style="' . $badge_style . '"></span>
                           <script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>';
            $to_render['content'] = $embed_code;
          }
        }
      }
    }
  return $to_render;
}
